apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-prod
  namespace: argocd
spec:
  destination:
    namespace: welcome-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/christianh814/welcome-deploy
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: welcome-prod
        server: https://kubernetes.default.svc
      source:
        path: overlays/prod
        repoURL: https://github.com/christianh814/welcome-deploy
        targetRevision: main
